name: Daily Task Trigger

on:
  schedule:
    - cron: '0 8 * * *'  # every day at 8:00 UTC

jobs:
  call-anvil-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call Anvil Endpoint
        run: curl -X GET https://frightened-prize-ship.anvil.app/_/api/daily_task
